# This workflow was based on quic-go's unit.yml

name: "Ginkgo Unit Tests"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        go: [ "1.20.x", "1.21.0-rc.4" ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - run: go version
    
    - name: Run tests
      env:
          TIMESCALE_FACTOR: 10
      run: go run github.com/onsi/ginkgo/v2/ginkgo -r -v -cover -randomize-all -randomize-suites -trace -skip-package integrationtests
    
    - name: Run tests (32 bit)
      if: ${{ matrix.os != 'macos' }} # can't run 32 bit tests on OSX.
      env:
        TIMESCALE_FACTOR: 10
        GOARCH: 386
      run: go run github.com/onsi/ginkgo/v2/ginkgo -r -v -cover -coverprofile coverage.txt -output-dir . -randomize-all -randomize-suites -trace -skip-package integrationtests
    
    - name: Run tests with race detector
      if: ${{ matrix.os == 'ubuntu' }} # speed things up. Windows and OSX VMs are slow
      env:
        TIMESCALE_FACTOR: 20
      run: go run github.com/onsi/ginkgo/v2/ginkgo -r -v -race -randomize-all -randomize-suites -trace -skip-package integrationtests